version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers-legacy
    steps:
      - checkout
      - run: yarn install
      - run: ./node_modules/.bin/jest __tests__/**/*.js
