version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-node8-alpha
    steps:
      - checkout
      - run: yarn install
      - run: yarn
  test:
    docker:
      - image: circleci/node:latest-browsers-legacy
    steps:
      - checkout
      - run:
          name: Load dependencies
          command: |
            brew update
            brew tap wix/brew
            brew install --HEAD applesimutils
            npm install -g detox-cli
      - run: yarn install
      - run: yarn detox:build
      - run: yarn detox:test:android:debug

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build
