version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers-legacy
    steps:
      - checkout
      - run: yarn install
  test:
    steps:
      - run: ./node_modules/.bin/jest __tests__/**/*.js

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
